from lab6a import (
    poly_add, poly_sub, poly_mul_monomial, poly_clean,
    leading_term, lex_cmp, grlex_cmp, poly_str_ordered, poly_mul,
)



def lcm_mono(a, b):
    return tuple(max(x, y) for x, y in zip(a, b))


def divides(exp_a, exp_b):
    return all(x <= y for x, y in zip(exp_a, exp_b))


def monomial_div(exp_dividend, c_dividend, exp_divisor, c_divisor):
    exp = tuple(a - b for a, b in zip(exp_dividend, exp_divisor))
    return exp, c_dividend / c_divisor


def polynomial_reduce(f, G, cmp_fn):
    n = len(G)
    alphas = [{} for _ in range(n)]
    r = {}
    p = dict(f)

    while p:
        lt_exp, lt_coeff = leading_term(p, cmp_fn)
        divided = False

        for i, g in enumerate(G):
            g_lt_exp, g_lt_coeff = leading_term(g, cmp_fn)
            if divides(g_lt_exp, lt_exp):
                q_exp, q_coeff = monomial_div(lt_exp, lt_coeff, g_lt_exp, g_lt_coeff)
                alphas[i][q_exp] = alphas[i].get(q_exp, 0) + q_coeff
                alphas[i] = poly_clean(alphas[i])
                p = poly_sub(p, poly_mul_monomial(g, q_exp, q_coeff))
                divided = True
                break

        if not divided:
            r[lt_exp] = r.get(lt_exp, 0) + lt_coeff
            del p[lt_exp]

    return alphas, poly_clean(r)


def s_polynomial(f, g, cmp_fn):
    lm_f, lc_f = leading_term(f, cmp_fn)
    lm_g, lc_g = leading_term(g, cmp_fn)

    lcm = lcm_mono(lm_f, lm_g)

    m_f = tuple(a - b for a, b in zip(lcm, lm_f))
    m_g = tuple(a - b for a, b in zip(lcm, lm_g))

    term_f = poly_mul_monomial(f, m_f, 1 / lc_f)
    term_g = poly_mul_monomial(g, m_g, 1 / lc_g)

    return poly_sub(term_f, term_g)



def buchberger(G, cmp_fn):
    """
    Compute a Grobner basis for the ideal generated by G under cmp_fn.
    """
    basis = list(G)
    pairs = [(i, j) for i in range(len(basis)) for j in range(i + 1, len(basis))]

    while pairs:
        i, j = pairs.pop(0)
        s = s_polynomial(basis[i], basis[j], cmp_fn)
        _, r = polynomial_reduce(s, basis, cmp_fn)
        if r:
            new_idx = len(basis)
            basis.append(r)
            for k in range(new_idx):
                pairs.append((k, new_idx))

    return basis

